[preface]
= Introducción

La idea de producir un documento que resumiera a modo de guía los pasos por los que ha de pasar todo piloto novel de VSM, surgió una tarde en la que un grupo comentábamos, bajo la arboleda del bar de Fuentemilanos, los avatares del día y la necesidad que muchos de nosotros experimentamos de disponer de más información sobre las distintas etapas que componen este período de aprendizaje, ciertamente intenso y emocionante.

Todos coincidimos en que los pilotos una vez "sueltos", han de enfrentarse en solitario con el VSM, y mirar con sensación de extrema lejanía a los pilotos más experimentados que vuelan tareas de 500, 700 ó 1.000 km, y que nos parecen inalcanzables, sobre todo cuando estamos en la etapa de "alas de plomo" y no somos capaces de mantenernos en el aire más de 20 ó 30 minutos después de soltarnos de la remolcadora.

En este trabajo realizado sin ánimo de lucro no cabe la presunción, puesto que la experiencia de unas pocas horas de vuelo no llegan ni para hacer recomendaciones a los compañeros de vuelo, pero sí que facultan para enumerar todas y cada una de las cuestiones y conceptos más significativos de esta etapa que todos pasamos para progresar en el VSM.

Compartimos el gran privilegio de poder disfrutar de esa experiencia entre místico y deportiva que es el VSM, y debemos sentirnos felices de dar a conocer las experiencias que tenemos, aunque sean bien pocas y modestas, y de facilitar a cualquiera el acceso a esta maravillosa actividad.

Saludos,